name: Build Resume PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  lint-latex:
    runs-on: ubuntu-latest
    steps:
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@1.0.3
       
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: LaTex Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          
      - name: Upload a Resume Zip Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: resume
          path: ${{ github.workspace }}/*.pdf

    
